name: ruff-format
on: [push, pull_request]
jobs:
  format:
    name: runner / ruff format
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Format files using Ruff
        uses: astral-sh/ruff-action@v4.0.0
        with:
          args: "format"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Format Python code with Ruff"
          commit-message: ":art: Format Python code with Ruff"
          body: |
            There appear to be some python formatting errors in ${{ github.sha }}. This pull request
            uses the [Ruff](https://github.com/astral-sh/ruff) formatter to fix these issues.
          base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch
          branch: actions/ruff-format
